### sign-up 
POST http://localhost:3001/site/sign-up
Content-Type: application/json

{
    "name": "Lê Minh Đại",
    "phone": "0387383584",
    "email": "louistart0ggy@gmail.com",
    "password": "123456789",
    "birthday": "13/06/2002",
    "avatar": "avatar.png",
    "gender": "nam",
    "address": "Long Annnnnnn"
}

### verify
PATCH http://localhost:3001/site/verify-email
Content-Type: application/json

{
    "email": "louistart0ggy@gmail.com",
    "otp": "dEcts0"
}

### login owner
POST http://localhost:3001/site/login
Content-Type: application/json

{
    "userName": "20521153@gm.uit.edu.vn",
    "password": "123456789"
}

### show store
GET http://localhost:3001/owner/store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTY4NzM1MzUwNywiZXhwIjoxNjg3MzU3MTA3fQ.-jRneSfELzYbbOcGin2JjvjvUOcVWT6YqfpWlhqGZhQ

### show employee by storeId
GET http://localhost:3001/owner/store/1/employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTY4NzM1MzUwNywiZXhwIjoxNjg3MzU3MTA3fQ.-jRneSfELzYbbOcGin2JjvjvUOcVWT6YqfpWlhqGZhQ

### show request 
GET http://localhost:3001/owner/show-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTY4NzM1MzUwNywiZXhwIjoxNjg3MzU3MTA3fQ.-jRneSfELzYbbOcGin2JjvjvUOcVWT6YqfpWlhqGZhQ


### accept request
PUT http://localhost:3001/owner/accept-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTY4NzM1MzUwNywiZXhwIjoxNjg3MzU3MTA3fQ.-jRneSfELzYbbOcGin2JjvjvUOcVWT6YqfpWlhqGZhQ
Content-Type: application/json

{
    "storeId":2,
    "freelancerId": 14
}

### find freelancer by phone
GET http://localhost:3001/owner/find-freelancer?phone=1234545566
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTY4NzM1MzUwNywiZXhwIjoxNjg3MzU3MTA3fQ.-jRneSfELzYbbOcGin2JjvjvUOcVWT6YqfpWlhqGZhQ

### send request
POST http://localhost:3001/owner/send-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTY4NzM0MDQ0MSwiZXhwIjoxNjg3MzQ0MDQxfQ.9eP5xp3DmK91QDJanfFciFWSNh14IU8xdDkzURaGO3o
Content-Type: application/json

{
    "storeId":2,
    "freelancerId": 14
}

### show emloyee group by store
GET http://localhost:3001/owner/show-empl-gr-store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTY4NzM1MzUwNywiZXhwIjoxNjg3MzU3MTA3fQ.-jRneSfELzYbbOcGin2JjvjvUOcVWT6YqfpWlhqGZhQ


### delete imployee is working in store
DELETE http://localhost:3001/owner/employee/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTY4NzM1MzUwNywiZXhwIjoxNjg3MzU3MTA3fQ.-jRneSfELzYbbOcGin2JjvjvUOcVWT6YqfpWlhqGZhQ
Content-Type: application/json

{
    "id":1
}