### sign-up
POST http://localhost:3001/site/sign-up
Content-Type: application/json

{
    "name": "Lê Minh Đại",
    "phone": "0387383583",
    "email": "20521153@gm.uit.edu.vn",
    "password": "123456789",
    "birthday": "13/06/2002",
    "avatar": "avatar.png",
    "gender": "nam",
    "address": "Long An"
}

### verify
PATCH http://localhost:3001/site/verify-email
Content-Type: application/json

{
    "email": "20521153@gm.uit.edu.vn",
    "otp": "gOAzjb"
}

### login
POST http://localhost:3001/site/login
Content-Type: application/json

{
    "userName": "20521153@gm.uit.edu.vn",
    "password": "123456789"
}